if (!window.NAMES) {
    NAMES = {};
}

NAMES['flowers'] = {
    "name": "Flowers",
    "source": "http://www.whatiscalled.com/flower-names-in-all-languages/",
    "values": [
        "Arabian Jasmine",
        "Lily",
        "Buttercups",
        "China Rose",
        "Cobra Saffron",
        "Crossandra",
        "Cypress Vine",
        "Daffodils",
        "Dahlia",
        "Daisy",
        "Damask Rose",
        "Datura",
        "Creeper",
        "Jasmine",
        "Four O'clock",
        "Frangipani",
        "Gallant Soldier",
        "Galinsoga Parviflora",
        "Globe Amaranth",
        "Golden Champa",
        "Indian Tulip",
        "Ixora",
        "Kewda",
        "Kurinji",
        "Violet",
        "Lotus",
        "Maloo Creeper",
        "Maulsari",
        "Midday Flower",
        "Oleander",
        "Peacock Flower",
        "Periwinkle",
        "Myrtle",
        "Rose",
        "Star Jasmine",
        "Sunflower",
        "Cassia",
        "Tulips",
        "Water Lily",
        "Bougainvillea",
        "Zinnia",
        "Ceylon Ironwood",
        "Bullet Wood",
        "Chrysanthemum",
        "Cockscomb",
        "Amaranth",
        "Pine",
        "Ghanera",
        "Hiptage",
        "Hummingbird Vine",
        "Chestnut",
        "Jungle Flame",
        "Pink Jasmine",
        "Star Glory",
        "Superb Lily",
        "Artichoke",
        "Chamomile",
        "Cannabis",
        "Citrus",
        "Blossoms",
        "Clover",
        "Dandelions",
        "Daylily",
        "Elderflower",
        "Hibiscus",
        "Honeysuckle",
        "Nasturtium",
        "Sweet",
        "Osmanthus",
        "Pansy",
        "Calendula",
        "Officinalis",
        "Sesbania",
        "Grandiflora",
        "Zucchini",
        "Aurantiaca",
        "Alba"
    ]
};