if (!window.NAMES) {
    NAMES = {};
}

NAMES['fishes'] = {
    "name": "Fishes & shellfishes",
    "source": "http://www.schmidtzeevis.nl/html/fish_names_in_7_languages.html",
    "values": [
        "Anchovy",
        "Perch",
        "Flounder",
        "Trout",
        "Garfish",
        "Gilt Head Bream",
        "Brill",
        "Coding",
        "Shark",
        "Mullet",
        "Herring",
        "Hake",
        "Halibut",
        "Horse Mackerel",
        "Octopus",
        "Squid",
        "Cuttlefish",
        "Cod",
        "Carp",
        "Caviar",
        "Saithe",
        "Frostfish",
        "Ling",
        "Capelin",
        "Mackerel",
        "Marlin",
        "Catfisch",
        "Goatfish",
        "Moray",
        "Croaker",
        "Drum",
        "Meagre",
        "Joey",
        "Eel",
        "Parrot fish",
        "Sardinella",
        "Weever",
        "Pilchard",
        "Plaice",
        "Tub gurnard",
        "Gurnard",
        "Eelpout",
        "Ray",
        "Skate",
        "Red Bream",
        "Sailfish",
        "Brisling",
        "Dab",
        "Haddock",
        "Scorpionfish",
        "Sandeel",
        "Pike",
        "Pike-perch",
        "Smelt",
        "Sprat",
        "Pout",
        "Sturgeon",
        "Stockfish",
        "John Dory",
        "Turbot",
        "Sole",
        "Tuna",
        "Bonito",
        "Filefish",
        "Triggerfish",
        "Pollack",
        "Flying Fish",
        "Whiting",
        "Silver hake",
        "Salmon",
        "Sea Bass",
        "Grouper",
        "Sea Bream",
        "Anglerfish",
        "Tench",
        "Conger",
        "Catfish",
        "Shrimp",
        "Crab",
        "Lobster",
        "Crawfish",
        "Periwinkle",
        "Scallop",
        "Cockle",
        "Mussel",
        "Oyster",
        "Razor shell",
        "clam",
        "Carpet Shell",
        "Hard Clam",
        "Whelk"
    ]
};