if (!window.NAMES) {
    NAMES = {};
}

NAMES['foods'] = {

    "name": "Foods (common)",
    "source": "https://en.wikipedia.org/wiki/Lists_of_foods",
    "values": [
        "Alfalfa",
        "Alfredo",
        "Angus",
        "Apple Juice",
        "Apple",
        "Artichoke",
        "Bagel",
        "Basil",
        "Bean",
        "Berry",
        "Biscuit",
        "Bread",
        "Brownie",
        "Burger",
        "Butter",
        "Butternut",
        "Cake",
        "Candy",
        "Caramel",
        "Carrot",
        "Cashew",
        "Cheese",
        "Cherry",
        "Chestnut",
        "Chicken",
        "Chickpea",
        "Chili",
        "Chip",
        "Chive",
        "Chocolate",
        "Churro",
        "Cinnamon",
        "Clementine",
        "Clove",
        "Coco",
        "Coconut",
        "Cookie",
        "Coriander",
        "Corn flakes",
        "Cranberry",
        "Crumpet",
        "Cupcake",
        "Curry",
        "Dumpling",
        "Eggs Benedict",
        "Eggs",
        "Espresso",
        "Fig",
        "Fish",
        "Flapjack",
        "French Fry",
        "Fritatta",
        "Fritter",
        "Ginger",
        "Gnocchi",
        "Grape Juice",
        "Guacamole",
        "Ham",
        "Hambone",
        "Hamburger",
        "Hazelnut",
        "Herb",
        "Honey",
        "Honeydew",
        "Jalapeño",
        "Jellybean",
        "Kale",
        "Kiwi",
        "Kumquat",
        "Lamb Chop",
        "Latke",
        "Lavender",
        "Lemon",
        "Linguini",
        "Macaroni",
        "Macaroon",
        "Mango",
        "Marshmallow",
        "Meatball",
        "Meatloaf",
        "Milk",
        "Muffin",
        "Mushroom",
        "Noodle",
        "Nori",
        "Nugget",
        "Nutmeg",
        "Olive",
        "Oregano",
        "Oreo",
        "Pancake",
        "Parsnip",
        "Peacan",
        "Peach",
        "Peanut",
        "Pepper",
        "Persimmon",
        "Pesto",
        "Pickled cucumber",
        "Pie",
        "Pierogi",
        "Pistachio",
        "Pizza",
        "Plum",
        "Popcorn",
        "Pork Chop",
        "Potato",
        "Praline",
        "Pudding",
        "Pumpkin",
        "Quiche",
        "Quince",
        "Quinoa",
        "Radish",
        "Raisin",
        "Ramen",
        "Ratatouille",
        "Rice",
        "Rosemary",
        "Saffron",
        "Sage",
        "Salad",
        "Salami",
        "Sandwich",
        "Sausages",
        "Schnitzel",
        "Shrimp",
        "Snicker",
        "Soup",
        "Soybean",
        "Spaghetti",
        "Spaguettis",
        "Steak",
        "Strawberry",
        "Sushi",
        "Sweet Pea",
        "Sweet Potato",
        "Taffy",
        "Thyme",
        "Toast",
        "Toffee",
        "Tofu",
        "Tomato",
        "Trix",
        "Tuna Steak",
        "Waffle",
        "Wasabi",
        "Ziti",
        "Zucchini"
    ]
};